name: Kuriimu2 Komponent

on:
  push:
    branches:
      - imgui
    paths:
      - 'src/lib/Komponent/*.nuspec'
      - 'src/lib/Komponent/*.csproj'
      - 'src/lib/Komponent/**/*.cs'
      - 'src/lib/Komponent.Contract/*.csproj'
      - 'src/lib/Komponent.Contract/**/*.cs'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2
    
    - name: Wait for other dev builds
      uses: softprops/turnstyle@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Build Nuget
      run: dotnet build ./src/lib/Komponent/Komponent.csproj --configuration Release

    - name: Publish Nuget
      run: |
        foreach($file in (Get-ChildItem "nuget" -Recurse -Include *.nupkg)) {
          dotnet nuget push $file --api-key ${{ secrets.NUGET_UPDATE }} --source https://nuget.pkg.github.com/FanTranslatorsInternational/index.json --skip-duplicate
        }
